### ISSUE TITLE
Regression / Identity: Judgements no longer possible

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#10493]
- [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Setting the judgement via the "Add identity judgement" link on an account's view no longer works.
The UI hangs.

<img width="716" alt="image" src="https://github.com/polkadot-js/apps/assets/738724/0e92951b-530a-4c21-a6d9-d70d4cb323a4">

with the error:
```
comm.88d5168f95c4b7c1.js:3892 Error: useCall(identity.identityOf):: Cannot read properties of undefined (reading 'hash'):: TypeError: Cannot read properties of undefined (reading 'hash')
    at transform (comm.88d5168f95c4b7c1.js:1724:919)
    at comm.88d5168f95c4b7c1.js:3892:41322
    at modu.c5e227c622fddc08.js:1:111325
    at modu.b05dd42ef8c37bcb.js:2:429403
    at u (comm.88d5168f95c4b7c1.js:3892:40118)
    at comm.88d5168f95c4b7c1.js:3892:41347
    at modu.c5e227c622fddc08.js:1:111325
    at modu.b05dd42ef8c37bcb.js:2:429403
```

* **What is the motivation for changing the behavior?**

I would rather have the behavior NOT change :)

* **Please tell us about your environment:**
  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by chevdor** [comment]
The issue can be seen on Polkadot and Kusama.
The selected RPC endpoint does not matter.

**Comment by TarikGul** [comment]
@chevdor Let me know if this fixes your issue. Happy to close once confirmed.

**Comment by chevdor** [comment]
It does fix the issue, thx.

**Comment by niklabh** [comment]
Sorry, this has broken polkadex and older chains now.

**Comment by TarikGul** [comment]
@niklabh I guess our best route is to check the type to see if its a tuple or not that either do the legacy option or the new one.
