### ISSUE TITLE
Preimages UI crashes after creating first preimage

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#10579]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Preimages UI crashes on recent runtime upgrade.

https://polkadot.js.org/apps/?rpc=wss://testnet-rpc-direct.tangle.tools#/preimages

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Assertion failed

Error: Assertion failed
at r (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:225)
at i._initArray (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:2142)
at i._init (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:1518)
at i (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:519)
at u (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:406276)
at d (https://polkadot.js.org/apps/modu.3003d44f5231b2ec.js:2:410063)
at m (https://polkadot.js.org/apps/comm.313f176df534a210.js:4043:750)
at https://polkadot.js.org/apps/comm.313f176df534a210.js:4084:644
at Pi (https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:77446)
at xl (https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:89067)
```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
To be clear you have only seen this on tangle network?

**Comment by ap211unitech** [comment]
Looks like it works fine for Tangle itself. Closing this issue now. Feel free to create a new issue if the problem persists.

https://github.com/user-attachments/assets/065b7400-906c-408a-a7be-1efb129e5332
