### ISSUE TITLE
Can't view democracy preimages

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#10793]
* **I'm submitting a bug report for error on Apps UI in democracy section**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Current behavior when viewing preimages is an error. It should show the preimage: https://polkadot.js.org/apps/?rpc=wss://rpc.tangle.tools#/preimages.
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Assertion failed

Error: Assertion failed
at r (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:225)
at a._initArray (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:2142)
at a._init (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:1518)
at new a (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:519)
at u (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:434287)
at d (https://polkadot.js.org/apps/modu.4279b36cc05eaea8.js:2:439473)
at m (https://polkadot.js.org/apps/comm.37b5596646059060.js:4047:750)
at https://polkadot.js.org/apps/comm.37b5596646059060.js:4088:644
at Pi (https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:77446)
at xl (https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:89067)
```

* **What is the motivation for changing the behavior?**

To fix the bug

* **Please tell us about your environment:**

Google chrome browser

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Seems like this is expected since the actual tab/route doesn't show up. This is because the actual chain doesn't have the necessary calls needed to run the preimage tab.

**Comment by drewstone** [comment]
I successfully created a preimage which caused this.. so not sure what you mean by "actual chain doesn't have the necessary calls needed". We even used the preimage to run the first democracy proposal. Can you elaborate @TarikGul ?

**Comment by TarikGul** [comment]
> I successfully created a preimage which caused this..

Good to know.

>  Can you elaborate

<img width="1722" alt="Screenshot 2024-08-14 at 6 29 20 PM" src="https://github.com/user-attachments/assets/ff6b1c84-c61a-49ba-ae3a-aa06faa67eb0">

The page doesn't have the tab for preimages so I assumed that might be the issue which is my bad. I was referencing this part: " Something went wrong with the query".

That being said this seems to be failing at BN.js:

```
Assertion failed
    at assert (webpack://@polkadot/apps/../../node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js?:7:21)
    at BN._initArray (webpack://@polkadot/apps/../../node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js?:146:5)
    at BN.init [as _init] (webpack://@polkadot/apps/../../node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js?:87:19)
    at BN (webpack://@polkadot/apps/../../node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js?:40:12)
    at bnToBn (webpack://@polkadot/apps/../../node_modules/@polkadot/util/bn/toBn.js?:45:31)
    at _formatBalance (webpack://@polkadot/apps/../../node_modules/@polkadot/util/format/formatBalance.js?:22:67)
    at applyFormat (webpack://@polkadot/apps/../react-query/src/FormatBalance.tsx?:43:92)
    at FormatBalance (webpack://@polkadot/apps/../react-query/src/FormatBalance.tsx?:64:31)
    at renderWithHooks (webpack://@polkadot/apps/../../node_modules/react-dom/cjs/react-dom.development.js?:16305:18)
    at updateFunctionComponent (webpack://@polkadot/apps/../../node_modules/react-dom/cjs/react-dom.development.js?:19583:20)
```

**Comment by TarikGul** [comment]
Ahh okay, i see. Some value from Preimages that is being sent to `FormatBalance` is a `Null` Type.
