### ISSUE TITLE
Polkadot Asset Balance & Transfers are not functioning

### ISSUE THREAD

**Issue by iamgenchi** [polkadot-js/apps#11097]
I'm submitting a bug in PolkadotJS on `polkadot.js.org` where Assets > Balances do not show in AssetHub.

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently the page doesn't load and the following error appears in the console.

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/836fb63e-33cc-4c61-8d3e-27536675b992">

```
comm.9d91dc48a36cf2d2.js:3910 Error: useCall(...):: Cannot read properties of undefined (reading '0'):: TypeError: Cannot read properties of undefined (reading '0')
    at transform (page.0830c174e132f19d.js:141:13026)
    at comm.9d91dc48a36cf2d2.js:3910:45057
    at modu.8f88b1c95873837b.js:1:161516
    at modu.99315fe9987024dd.js:2:481239
    at transform (page.0830c174e132f19d.js:141:13026)
    at comm.9d91dc48a36cf2d2.js:3910:45057
    at modu.8f88b1c95873837b.js:1:161516
    at modu.99315fe9987024dd.js:2:481239
    at u (comm.9d91dc48a36cf2d2.js:3910:43853)
    at comm.9d91dc48a36cf2d2.js:3910:45082
    at modu.8f88b1c95873837b.js:1:161516
    at modu.99315fe9987024dd.js:2:481239
```

* **What is the motivation for changing the behavior?**

Currently we cannot send assets in AssetHub (for example USDT or USDC) if this is not fixed.

* **Please tell us about your environment:**

MacOS Sequoia 15.0.1 (24A348) - Chrome Version 130.0.6723.117

polkadot-parachain v1.16.2
api v14.3.1
apps v0.146.2-0

    - [x] Browser

**Comment by IkerAlus** [comment]
Duplicated of https://github.com/polkadot-js/apps/issues/10476
