### ISSUE TITLE
Errors when connect to node-template project

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1587]
New project generated with `curl https://raw.githubusercontent.com/paritytech/substrate-up/d4a258a3b7069f92228a245477fed914334c9b82/substrate-node-new -sSf | sh -s test test`
i.e. based on substrate commit ac6a2a783

polkadot apps have those errors in console

```
VM16:37 query.session.validators :: s: Unable to find api.query.session.validators
    at t.default (https://polkadot.js.org/apps/main.4883dc2f.js:21:134847)
    at Object.getApiMethod (https://polkadot.js.org/apps/main.4883dc2f.js:21:233357)
    at Object.subscribe (https://polkadot.js.org/apps/main.4883dc2f.js:21:233840)
```

```
VM16:37 query.staking.bonded :: s: Unable to find api.query.staking.bonded
    at t.default (https://polkadot.js.org/apps/main.4883dc2f.js:21:134847)
    at Object.getApiMethod (https://polkadot.js.org/apps/main.4883dc2f.js:21:233357)
    at Object.subscribe (https://polkadot.js.org/apps/main.4883dc2f.js:21:233840)
```

**Comment by jacogr** [comment]
Yes, it is known. All those have fallbacks. It always logs when it doesn't find something - the alternative would be to not log, however then you end up with passing functions that will never work and no alerts on those. So irritating . as it is, it does add some protection in the cases where you unknowingly make a mistake.

**Comment by xlc** [comment]
Can you make it warning level instead of error level?
