### ISSUE TITLE
Unable to initialize the API: Unable to find plain type for {"info":6,"type":"AuthorityList"}

### ISSUE THREAD

**Issue by starit** [polkadot-js/apps#1860]
I created a new project and only installed @polkadot/api. I wrote subscribe blocks related code (from official website) and it shows the following error when I start to run:
```
Unknown types found, no types for AuthorityList
2019-11-09 12:51:18   API/DECORATOR: Error: FATAL: Unable to initialize the API: Unable to find plain type for {"info":6,"type":"AuthorityList"}
    at EventEmitter.Init._onProviderConnect (/Users/starit/src/substrate/api-test/node_modules/@polkadot/api/base/Init.js:88:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by starit** [comment]
BTW, I subscribed kusama...

**Comment by jacogr** [comment]
See this API FAQ entry https://polkadot.js.org/api/start/FAQ.html#i-am-getting-a-unknown-types-found-no-types-for-error
