### ISSUE TITLE
Error: No valid exports main found for 'nanoid'

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/apps#2735]
Repro:
- clean git clone
- yarn install
- yarn start

Got:
```
yarn start
/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: No valid exports main found for '/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/nanoid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-plugin-serve/lib/index.js:18:28)
    at Module._compile (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/amaurymartiny/Workspaces/polkadot/apps/packages/apps/webpack.config.js:14:32)
    at Module._compile (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/amaurymartiny/Workspaces/polkadot/apps/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'MODULE_NOT_FOUND'
}
```

- node -v: v13.6.0
- yarn -v: 2.0.0-rc.33
- macos 10.15.4

**Comment by amaurymartiny** [comment]
nvm use 12.14.1 fixed it.
