### ISSUE TITLE
Sending custom RPCs to live network

### ISSUE THREAD

**Issue by JosephDenman** [polkadot-js/apps#5303]
I'm trying to connect to the SORA network and send a custom RPC that SORA has defined. The documentation for creating and extending the Polkadot RPCs is clear. Less clear is how clients can construct and send the RPCs that a network has defined. When I connect to the SORA network using

```
import { ApiPromise, WsProvider } from '@polkadot/api';

const wsProvider = new WsProvider('wss://sora.lux8.net');
const api = await ApiPromise.create({ provider: wsProvider });
```

I see

```
2021-05-16 11:56:50        REGISTRY: Unable to resolve type DispatchResultWithPostInfo, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type MultiCurrencyBalance, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type CurrencyId, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type CurrencyIdOf, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type AmountOf, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type DEXId, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type TradingPair, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type TechAssetId, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type TechAccountId, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type LiquiditySourceType, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        REGISTRY: Unable to resolve type Fixed, it will fail on construction
/Users/josephdenman/node_modules/@polkadot/util/logger.js:47
2021-05-16 11:56:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(CurrencyIdOf):: Cannot construct unknown type CurrencyIdOf
    at EventEmitter.value (/Users/josephdenman/node_modules/@polkadot/api/base/Init.js:73:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {stack: 'Error: FATAL: Unable to initialize the API: c…ctions (internal/process/task_queues.js:93:5)', message: 'FATAL: Unable to initialize the API: createT…: Cannot construct unknown type CurrencyIdOf'}
2021-05-16 11:56:50        API/INIT: Error: createType(CurrencyIdOf):: Cannot construct unknown type CurrencyIdOf
```

Clearly I'm missing the type definitions locally, but I'm unsure what I need to construct them. Can someone explain to me in detail the pieces that I need and how to put them together? Or point me to documentation describing how to do so?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/start/types.extend

**Comment by JosephDenman** [comment]
Suppose I have the JSON definition of the types: https://github.com/sora-xor/sora2-types/blob/master/sora2_types.json

Do I need to this to the format described here?: https://polkadot.js.org/docs/api/start/types.extend

**Comment by jacogr** [comment]
Yes, it needs to be in the standard format the JS API accepts and as is documented, the above is not valid, e.g. compare the definition of struct types.

**Comment by JosephDenman** [comment]
Ok. Is there a grammar for the definition syntax somewhere? I'm seeing constructs that don't appear in the examples. For example, `type_mapping: [ ... ]`. What language is this specification? It doesn't seem like Typescript because my editor doesn't recognize `_enum`, only `enum`.

**Comment by jacogr** [comment]
No, idea, those are not Js types. I would suggest to refer the question to that team, since it is their construct. (It seems like the syntax for the Python API type definitions) 

The link I shared is the only syntax the JS API can properly use for correct types.

**Comment by JosephDenman** [comment]
Ok. So there's no complete grammar for the definition language? What language are the Edgeware custom type definitions written in? It doesn't look like Typescript.

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/start/types.extend/ - that is the documentation that all teams use.
