### ISSUE TITLE
polkadotjs appImage doesn't launch since update to 92.1

### ISSUE THREAD

**Issue by mikakun** [polkadot-js/apps#5504]
using the appimage on ubuntu 20 (launching from the command line)

`mika@mika-C40:~/Bureau$ ./Polkadot-JS-Apps-0.92.1.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/.mount_PolkadIygWRv/resources/app.asar/packages/apps-electron/build/electron.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Object.<anonymous> (electron/js2c/browser_init.js:197:3336)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:197:3540)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!`

**Comment by blxxd** [comment]
Same but slightly different error. Version 0.91.2 works fine
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/.mount_PolkadRDftdN/resources/app.asar/packages/apps-electron/build/electron.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Object.<anonymous> (electron/js2c/browser_init.js:197:3336)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:197:3540)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
```

**Comment by jacogr** [comment]
This is one of those where I'm completely lost to try an debug. Certainly seems like an issue.

**Comment by heisler98** [comment]
Experiencing same issue. Launch would occasionally work via GUI, but Terminal launch (necessary for use w/ Parity Signer, as electron somehow stops macOS camera permission requests) always failed with the same error as above. I excised the auto-updater code and rebuilt 0.91.2 – is there a flag to stop auto-updating?

**Comment by wmshukri85** [comment]
Same Issue with me.

**Comment by michalisFr** [comment]
Adding for consistency that this happens on Windows and macOS too.

**Comment by rbdemarch** [comment]
Any idea on how to fix this?

**Comment by jacogr** [comment]
Will make a patch release in a couple of hours that will hopefully resolve it. (Based on the linked PR that was merged)

**Comment by jacogr** [comment]
0.92.3 with the builder downgrade works for me again on Mac.

**Comment by mikakun** [comment]
ok on ubuntu

still some warning though
```

mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
```
