### ISSUE TITLE
Cannot yarn run start `worker_threads`

### ISSUE THREAD

**Issue by decentration** [polkadot-js/apps#7052]
im clong polkadot-js apps and getting this error when running `yarn`

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /root/apps/.yarn/releases/yarn-3.1.1.cjs:426:2642
    at Object.<anonymous> (/root/apps/.yarn/releases/yarn-3.1.1.cjs:723:7786)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    ```

**Comment by jacogr** [comment]
Really no idea, never seen it before.

**Comment by decentration** [comment]
I solved this by updating nvm : )
