### ISSUE TITLE
BUG: Build is failing with latest node and yarn versions

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/apps#7054]
**Build is failing with latest node and yarn versions.** 
Node : v17.6.0
Yarn : 3.1.1
OS: Ubuntu 18

**LOGS** 
---

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): http://45.77.23.61:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/root/apps/packages/apps/build' directory
(node:29996) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
assets by path locales/ 1.88 MiB
  assets by path locales/en/*.json 191 KiB
    asset locales/en/app-accounts.json 39 KiB [emitted] [from: public/locales/en/app-accounts.json] [copied]
    + 38 assets
  + 14 assets
assets by info 30.9 MiB [immutable]
  assets by path *.js 30.2 MiB 19 assets
  assets by path *.cjs 10.2 KiB 14 assets
  asset react.01.e70314ae.css 613 KiB [emitted] [immutable] [big] (name: react.01) (id hint: react1)
assets by path ipfs/ 699 bytes
  asset ipfs/index.html 580 bytes [emitted] [from: public/ipfs/index.html] [copied]
  asset ipfs/pin.json 119 bytes [emitted] [from: public/ipfs/pin.json] [copied]
asset favicon.ico 37.2 KiB [emitted] [from: public/favicon.ico] [copied]
asset index.html 3.24 KiB [emitted] [from: public/index.html] [copied]
asset manifest.json 337 bytes [emitted] [from: public/manifest.json] [copied]
Entrypoint main [big] 25.7 MiB (10.2 KiB) = 13 assets 14 auxiliary assets
orphan modules 875 KiB (javascript) 4.21 KiB (asset) [orphan] 589 modules
runtime modules 60.4 KiB 29 modules
javascript modules 22.8 MiB 5122 modules
asset modules 1010 bytes (javascript) 14.6 KiB (asset)
  ../../node_modules/@polkadot/ui-settings/index.cjs 42 bytes (javascript) 702 bytes (asset) [built] [code generated]
  ../../node_modules/@polkadot/util/index.cjs 42 bytes (javascript) 447 bytes (asset) [built] [code generated]
  + 22 modules
json modules 178 KiB
  optional modules 159 KiB [optional] 10 modules
  modules by path ../../node_modules/@equilab/definitions/ 13.1 KiB 3 modules
  + 4 modules
css modules 613 KiB
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css 99 bytes [built] [code generated]
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css (1) 613 KiB [built] [code generated]

ERROR in ../apps-config/src/ui/logos/chains/acala.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 10:0-44 345:16-26 416:18-28 526:9-19 636:15-25
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/aleph.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 11:0-44 180:16-26 181:24-34 528:9-19
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/altair.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 12:0-46 182:10-21 530:10-21
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/efinity.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 18:0-48 209:11-23
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/equilibrium.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 19:0-56 210:15-31 211:22-38 217:29-45 564:15-31
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/genshiro.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 21:0-50 216:12-25 571:12-25 651:18-31
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/interlay.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 23:0-50 226:12-25 399:12-25 579:12-25 654:18-31
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/karura.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 24:0-46 230:10-21 582:10-21
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/parallel.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 31:0-50 279:12-25 280:20-33 574:9-22 616:12-25
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

**Comment by jacogr** [comment]
Have not run into it myself (I'm still on LTS), however SO yields some answers - https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

The Webpack issue - https://github.com/webpack/webpack/issues/14532

(Google actually has a lot of these threads, have not delved through all to see what the underlying solution might be)

**Comment by jacogr** [comment]
Try this branch to see if it solves it for you - https://github.com/polkadot-js/apps/pull/7056

**Comment by muddlebee** [comment]
@jacogr didn't work. same issue. Although its running fine with the docker deployment..

LOGS
---
```
$ polkadot-dev-clean-build 
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): http://45.77.23.61:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/root/apps/packages/apps/build' directory
(node:26219) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
assets by path locales/ 1.88 MiB
  assets by path locales/en/*.json 191 KiB
    asset locales/en/app-accounts.json 39 KiB [emitted] [from: public/locales/en/app-accounts.json] [copied]
    + 38 assets
  + 14 assets
assets by info 30.9 MiB [immutable]
  assets by path *.js 30.2 MiB 19 assets
  assets by path *.cjs 10.2 KiB 14 assets
  asset react.01.e70314ae.css 613 KiB [emitted] [immutable] [big] (name: react.01) (id hint: react1)
assets by path ipfs/ 699 bytes
  asset ipfs/index.html 580 bytes [emitted] [from: public/ipfs/index.html] [copied]
  asset ipfs/pin.json 119 bytes [emitted] [from: public/ipfs/pin.json] [copied]
asset favicon.ico 37.2 KiB [emitted] [from: public/favicon.ico] [copied]
asset index.html 3.24 KiB [emitted] [from: public/index.html] [copied]
asset manifest.json 337 bytes [emitted] [from: public/manifest.json] [copied]
Entrypoint main [big] 25.7 MiB (10.2 KiB) = 13 assets 14 auxiliary assets
orphan modules 875 KiB (javascript) 4.21 KiB (asset) [orphan] 589 modules
runtime modules 60.4 KiB 29 modules
javascript modules 22.8 MiB 5122 modules
asset modules 1010 bytes (javascript) 14.6 KiB (asset)
  ../../node_modules/@polkadot/ui-settings/index.cjs 42 bytes (javascript) 702 bytes (asset) [built] [code generated]
  ../../node_modules/@polkadot/util/index.cjs 42 bytes (javascript) 447 bytes (asset) [built] [code generated]
  + 22 modules
json modules 178 KiB
  optional modules 159 KiB [optional] 10 modules
  modules by path ../../node_modules/@equilab/definitions/ 13.1 KiB 3 modules
  + 4 modules
css modules 613 KiB
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css 99 bytes [built] [code generated]
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css (1) 613 KiB [built] [code generated]

ERROR in ../apps-config/src/ui/logos/chains/acala.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 10:0-44 345:16-26 416:18-28 526:9-19 636:15-25
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/aleph.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 11:0-44 180:16-26 181:24-34 528:9-19
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/altair.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 12:0-46 182:10-21 530:10-21
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24

ERROR in ../apps-config/src/ui/logos/chains/efinity.svg
Module build failed (from ../../node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at getHashDigest (/root/apps/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /root/apps/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/root/apps/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/root/apps/node_modules/file-loader/dist/index.js:29:48)
 @ ../apps-config/src/ui/logos/index.ts 18:0-48 209:11-23
 @ ../apps-config/src/ui/index.ts 6:0-24 6:0-24
 @ ../apps-config/src/index.ts 8:0-21 8:0-21
 @ ./src/initSettings.ts 5:0-58 32:20-37
 @ ./src/index.tsx 4:0-24


```

**Comment by muddlebee** [comment]
```
root@vultr:~/apps# git branch
* jg-loader-hash
  master
root@vultr:~/apps# 
```

**Comment by jacogr** [comment]
Basically the options listed by the Webpack issue (where this originates) is one of -

- downgrade node
- wait for Webpack 6 (here we are on the latest 5.x release)
- swap to xxHash

will update that branch to swap all hashing to xxHash and ask you to retry (sorry for asking you to play tester, just don’t want to break my env, as horrible as it is having an upstream issue)

**Comment by muddlebee** [comment]
@jacogr naah its cool. 😄 

 Not the first time Im seeing such compatibility issues with node environment. And yes downgrading to LTS version always works 👍 
 
 Thanks for the updates 🎉

**Comment by jacogr** [comment]
Sorry for the delay in getting back here. I updated https://github.com/polkadot-js/apps/pull/7056 to include the `output.hashFunction` as suggested here - https://github.com/webpack/webpack/issues/14532#issuecomment-947525539

Would appreciate a test.

**Comment by wirednkod** [comment]
Tried to figureout if this still works and tested with:
```
➜  apps git:(master) yarn -v
3.2.0
➜  apps git:(master) node -v
v17.6.0
```

Normal and electron builds worked correctly. See build logs below:
 ```sh
 ➜  apps git:(master) yarn run build
i18next-scanner: options={
  "debug": true,
  "sort": false,
  "attr": {
    "list": [
      "data-i18n"
    ],
    "extensions": [
      ".html",
      ".htm"
    ]
  },
  "func": {
    "extensions": [
      ".tsx",
      ".ts"
    ],
    "list": [
      "t",
      "i18next.t",
      "i18n.t"
    ]
  },
  "trans": {
    "component": "Trans",
    "i18nKey": "i18nKey",
    "defaultsKey": "defaults",
    "extensions": [
      ".js",
      ".jsx"
    ],
    "fallbackKey": false,
    "acorn": {
      "ecmaVersion": 2020,
      "sourceType": "module"
    }
  },
  "lngs": [
    "en"
  ],
  "fallbackLng": "en",
  "ns": [
    "apps",
    "apps-config",
    "apps-electron",
    "apps-routing",
    "app-accounts",
    "app-addresses",
    "app-assets",
    "app-bounties",
    "app-calendar",
    "app-claims",
    "app-contracts",
    "app-council",
    "app-democracy",
    "app-explorer",
    "app-extrinsics",
    "app-files",
    "app-gilt",
    "app-js",
    "app-membership",
    "app-nfts",
    "app-parachains",
    "app-poll",
    "app-rpc",
    "app-settings",
    "app-signing",
    "app-society",
    "app-staking",
    "app-storage",
    "app-sudo",
    "app-tech-comm",
    "app-treasury",
    "react-api",
    "react-components",
    "react-hooks",
    "react-params",
    "react-query",
    "react-signer",
    "test-support",
    "translation"
  ],
  "defaultLng": "en",
  "defaultNs": "translation",
  "defaultValue": "",
  "resource": {
    "jsonIndent": 2,
    "lineEnding": "\n",
    "loadPath": "packages/apps/public/locales/{{lng}}/{{ns}}.json",
    "savePath": "packages/apps/public/locales/{{lng}}/{{ns}}.json"
  },
  "keySeparator": false,
  "nsSeparator": false,
  "context": true,
  "contextFallback": true,
  "contextSeparator": "_",
  "contextDefaultValues": [],
  "plural": true,
  "pluralFallback": true,
  "pluralSeparator": "_",
  "interpolation": {
    "prefix": "{{",
    "suffix": "}}"
  }
}
$ polkadot-dev-build-ts 
$ yarn polkadot-dev-clean-build
$ polkadot-dev-clean-build 
$ yarn polkadot-exec-tsc --build tsconfig.build.json
$ tsc --build tsconfig.build.json
*** @polkadot/apps 0.110.1
$ yarn polkadot-exec-webpack --config webpack.config.cjs --mode production
$ yarn webpack --config webpack.config.cjs --mode production
assets by path static/*.png 12.8 MiB 1611 assets
assets by path static/*.svg 590 KiB
  asset static/moonriver.0d6c0ca2..svg 257 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/moonriver.svg] [big] (auxiliary name: main)
  asset static/hanonycash.3eb00ba5..svg 54.7 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/hanonycash.svg] (auxiliary name: main)
  asset static/laminar-circle.55590ac9..svg 29.5 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/laminar-circle.svg] (auxiliary name: main)
  + 76 assets
assets by path locales/ 1.88 MiB
  assets by path locales/en/*.json 191 KiB
    asset locales/en/app-accounts.json 38.1 KiB [emitted] [from: public/locales/en/app-accounts.json] [copied]
    + 39 assets
  + 14 assets
assets by path *.js 9.98 MiB
  assets by status 9.01 MiB [big] 9 assets
  + 10 assets
+ 7 assets
Entrypoint main [big] 5.79 MiB (13.3 MiB) = 13 assets 1691 auxiliary assets
orphan modules 7.81 MiB (javascript) 937 bytes (runtime) [orphan] 2445 modules
runtime modules 7.66 KiB 14 modules
modules by path ../ 12 MiB (javascript) 13.8 MiB (asset) 613 KiB (css/mini-extract)
  asset modules 69.9 KiB (javascript) 13.8 MiB (asset) 1704 modules
  modules by path ../../node_modules/ 12 MiB (javascript) 613 KiB (css/mini-extract)
    javascript modules 11.8 MiB 1625 modules
    json modules 179 KiB 17 modules
    modules by path ../../node_modules/semantic-ui-css/ 613 KiB 2 modules
  ../react-components/src/IdentityIcon/RoboHash/backgrounds/index.ts 1.15 KiB [built] [code generated]
modules by path ./ 2.47 MiB
  ./src/index.tsx + 1087 modules 2.47 MiB [built] [code generated]
  ./package.json 1.38 KiB [built] [code generated]
+ 8 modules
webpack 5.70.0 compiled successfully in 17401 ms

*** @polkadot/apps-config 0.110.1
Successfully compiled 183 files with Babel (1087ms).
Successfully compiled 183 files with Babel (407ms).
Successfully built exports (29ms)
Successfully linted configs (32ms)

*** @polkadot/apps-electron 0.110.1

*** @polkadot/apps-routing 0.110.1

*** @polkadot/app-accounts 0.110.1

*** @polkadot/app-addresses 0.110.1

*** @polkadot/app-assets 0.110.1

*** @polkadot/app-bounties 0.110.1

*** @polkadot/app-calendar 0.110.1

*** @polkadot/app-claims 0.110.1

*** @polkadot/app-contracts 0.110.1

*** @polkadot/app-council 0.110.1

*** @polkadot/app-democracy 0.110.1

*** @polkadot/app-explorer 0.110.1

*** @polkadot/app-extrinsics 0.110.1

*** @polkadot/app-files 0.110.1

*** @polkadot/app-gilt 0.110.1

*** @polkadot/app-js 0.110.1

*** @polkadot/app-membership 0.110.1

*** @polkadot/app-nfts 0.110.1

*** @polkadot/app-parachains 0.110.1

*** @polkadot/app-poll 0.110.1

*** @polkadot/app-rpc 0.110.1

*** @polkadot/app-settings 0.110.1

*** @polkadot/app-signing 0.110.1

*** @polkadot/app-society 0.110.1

*** @polkadot/app-staking 0.110.1

*** @polkadot/app-storage 0.110.1

*** @polkadot/app-sudo 0.110.1

*** @polkadot/app-tech-comm 0.110.1

*** @polkadot/app-treasury 0.110.1

*** @polkadot/react-api 0.110.1

*** @polkadot/react-components 0.110.1

*** @polkadot/react-hooks 0.110.1

*** @polkadot/react-params 0.110.1

*** @polkadot/react-query 0.110.1

*** @polkadot/react-signer 0.110.1

*** @polkadot/test-support 0.110.1
```

and 
```sh
➜  apps git:(master) yarn run build:electron
$ polkadot-dev-clean-build 
assets by chunk 238 KiB (id hint: vendors)
  asset 882.js 218 KiB [emitted] [minimized] (id hint: vendors) 1 related asset
  asset 436.js 19.9 KiB [emitted] [minimized] (id hint: vendors)
asset icon.png 46.9 KiB [emitted] [from: assets/icon.png] [copied]
asset electron.js 8.01 KiB [emitted] [minimized] (name: electron)
asset preload.js 333 bytes [emitted] [minimized] (name: preload)
orphan modules 239 KiB [orphan] 154 modules
runtime modules 3.54 KiB 9 modules
built modules 616 KiB [built]
  modules by path ../../node_modules/ 606 KiB 177 modules
  modules by path ./src/ 8.53 KiB
    ./src/electron/index.ts + 8 modules 8.01 KiB [built] [code generated]
    ./src/preload.ts + 1 modules 535 bytes [not cacheable] [built] [code generated]
  + 19 modules
webpack 5.70.0 compiled successfully in 2462 ms
assets by path static/*.png 12.8 MiB 1611 assets
assets by path static/*.svg 590 KiB
  asset static/moonriver.0d6c0ca2..svg 257 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/moonriver.svg] [big] (auxiliary name: main)
  asset static/hanonycash.3eb00ba5..svg 54.7 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/hanonycash.svg] (auxiliary name: main)
  asset static/laminar-circle.55590ac9..svg 29.5 KiB [emitted] [immutable] [from: ../apps-config/src/ui/logos/nodes/laminar-circle.svg] (auxiliary name: main)
  + 76 assets
assets by path locales/ 1.88 MiB
  assets by path locales/en/*.json 191 KiB 40 assets
  + 14 assets
assets by path *.js 22.4 MiB
  assets by status 22 MiB [big]
    assets by chunk 4.84 MiB (id hint: vendors) 3 assets
    + 11 assets
  + 5 assets
+ 7 assets
Entrypoint main [big] 17.9 MiB (13.3 MiB) = 13 assets 1691 auxiliary assets
orphan modules 1.47 MiB (javascript) 937 bytes (runtime) [orphan] 612 modules
runtime modules 8.73 KiB 17 modules
javascript modules 15.4 MiB 3476 modules
asset modules 69.9 KiB (javascript) 13.8 MiB (asset)
  modules by path ../react-components/src/IdentityIcon/RoboHash/sets/ 62.1 KiB (javascript) 7.3 MiB (asset) 1513 modules
  modules by path ../apps-config/src/ 6.97 KiB (javascript) 6.1 MiB (asset) 170 modules
  modules by path ../react-components/src/IdentityIcon/RoboHash/backgrounds/ 840 bytes (javascript) 439 KiB (asset) 20 modules
  ../react-components/src/Spinner.png 42 bytes (javascript) 11.5 KiB (asset) [built] [code generated]
json modules 180 KiB
  optional modules 159 KiB [optional] 10 modules
  modules by path ../../node_modules/@equilab/definitions/ 13.1 KiB 3 modules
  + 5 modules
css modules 613 KiB
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css 99 bytes [built] [code generated]
  css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.min.css (1) 613 KiB [built] [code generated]
webpack 5.70.0 compiled successfully in 7760 ms
```

**Comment by jacogr** [comment]
Thank you. Will get it in master.
