### ISSUE TITLE
Uncaught error on accounts page

### ISSUE THREAD

**Issue by sander2** [polkadot-js/apps#7065]
We are getting uncaught errors on the account page: [easily reproducible here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/accounts).

Personally, I am getting this error:

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

y.namedReserves is undefined
is@https://polkadot.js.org/apps/main.dd27c9fa.js:2:448239
rs@https://polkadot.js.org/apps/main.dd27c9fa.js:2:451765
17614/ls<@https://polkadot.js.org/apps/main.dd27c9fa.js:2:452393
aa@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:313829
Ua@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:323347
$s@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:366852
Bl@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:353154
Pl@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:353082
Sl@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:352943
ml@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:349930
52967/qo/<@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:299751
46475/t.unstable_runWithPriority@https://polkadot.js.org/apps/other.01.e3c640b8.js:2:86371
Wo@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:299528
qo@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:299698
Ko@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:299631
dl@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:347315
enqueueSetState@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:303605
83426/m.prototype.setState@https://polkadot.js.org/apps/react.01.39fdd46e.js:2:602247
nextState@https://polkadot.js.org/apps/main.dd27c9fa.js:2:426375
triggerUpdate@https://polkadot.js.org/apps/main.dd27c9fa.js:2:428168
p@https://polkadot.js.org/apps/main.dd27c9fa.js:2:427737
10589/u/</</u</<@https://polkadot.js.org/apps/polkadot.01.f558152e.js:1:101241
```

Other people have reported other errors on the same page:

![image](https://user-images.githubusercontent.com/2421693/155941350-1c709b3c-760f-449c-91df-4be51c344ded.png)

**Comment by jacogr** [comment]
The custom balance derive does not return the namedReserves as per the API derive. This needs adjustment - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/interbtc.ts#L50

**Comment by StrawberryFlavor** [comment]
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

(e || []).map is not a function

TypeError: (e || []).map is not a function
at $9 (https://polkadot.js.org/apps/main.dd27c9fa.js:2:552070)
at https://polkadot.js.org/apps/main.dd27c9fa.js:2:552321
at Object.ga [as useState] (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:317109)
at t.useState (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:606835)
at eee (https://polkadot.js.org/apps/main.dd27c9fa.js:2:552315)
at aa (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:313829)
at Ua (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:323347)
at za (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:322681)
at Fa (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:322339)
at $s (https://polkadot.js.org/apps/react.01.39fdd46e.js:2:369109)
```
