### ISSUE TITLE
Extrinsic Construction Fails with XCM V2 Message

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#7070]
![image](https://user-images.githubusercontent.com/25483142/155987429-deafa31c-6757-4391-a724-e296ee240cb9.png)

Block/runtime:
![image](https://user-images.githubusercontent.com/25483142/155987507-7440b58a-ee0f-417b-8002-9f3faaa9ff05.png)

Client/API:
![image](https://user-images.githubusercontent.com/25483142/155987530-1d591017-9d45-4973-b352-affd210c515c.png)

Provider: Parity
![image](https://user-images.githubusercontent.com/25483142/155987594-356c6694-b781-48fe-a421-f447c7b3c965.png)

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

(e || []).map is not a function

TypeError: (e || []).map is not a function
at $9 (https://polkadot.js.org/apps/main.f69ce64f.js:2:552094)
at https://polkadot.js.org/apps/main.f69ce64f.js:2:552345
at Object.ga [as useState] (https://polkadot.js.org/apps/react.01.7866035b.js:2:317109)
at t.useState (https://polkadot.js.org/apps/react.01.7866035b.js:2:606835)
at eee (https://polkadot.js.org/apps/main.f69ce64f.js:2:552339)
at aa (https://polkadot.js.org/apps/react.01.7866035b.js:2:313829)
at Ua (https://polkadot.js.org/apps/react.01.7866035b.js:2:323347)
at za (https://polkadot.js.org/apps/react.01.7866035b.js:2:322681)
at Fa (https://polkadot.js.org/apps/react.01.7866035b.js:2:322339)
at $s (https://polkadot.js.org/apps/react.01.7866035b.js:2:369109)
```

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/7069
