### ISSUE TITLE
View block not working: Unable to determine type from 'U64'

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#770]
Dried Danta

https://polkadot.js.org/apps/#/explorer/hash/0x5805e91f63d259acc39cf39d348b3d42d07c3098209d4c2baae4640ca033ffbc

```
o: Unable to determine type from 'U64'
    at e.default (https://polkadot.js.org/apps/main.a8eb7124.js:27:167675)
    at Q (https://polkadot.js.org/apps/main.a8eb7124.js:27:134454)
    at d (https://polkadot.js.org/apps/main.a8eb7124.js:27:134527)
    at e.default (https://polkadot.js.org/apps/main.a8eb7124.js:27:132261)
    at e.default (https://polkadot.js.org/apps/main.a8eb7124.js:27:213438)
    at getDerivedStateFromProps (https://polkadot.js.org/apps/main.a8eb7124.js:69:14771)
    at oa (https://polkadot.js.org/apps/react.4119fa2a.js:25:44371)
    at ca (https://polkadot.js.org/apps/react.4119fa2a.js:25:46155)
    at Eo (https://polkadot.js.org/apps/react.4119fa2a.js:25:60085)
    at Do (https://polkadot.js.org/apps/react.4119fa2a.js:25:66534)
window.console.error @ VM71:37
15:18:56.952 VM71:37 rpc.chain.getBlock :: Unable to determine type from 'U64'
window.console.error @ VM71:37
```

**Comment by jacogr** [comment]
So apps also try and determine "unknown" types via instance now, using createType. However, it seems like the fact that we are using `U64` in JS (types) as opposed to the `u64` finally got us into trouble.

Will make it work from a API side (i.e. having both types), however probably needs a consistency look there at some point. For now, get a fix in first and foremost.
