### ISSUE TITLE
Running in production (update ReadMe)

### ISSUE THREAD

**Issue by Ethereumx** [polkadot-js/apps#8093]
I am wondering how to run the app in production as only dev instructions are indicated in the Readme file?

**Comment by jacogr** [comment]
1.  yarn build
2. deploy packages/apps/build

**Comment by Ethereumx** [comment]
Thanks for the clarification.
When building (node 16, yarn 1.22) I am getting :

```
packages/apps-config/src/endpoints/index.ts:9:1 - error TS6192: All imports in import declaration are unused.

9 import { prodChains, prodRelayKusama, prodRelayPolkadot } from './production';
.
.
Found 13 errors.

Error: Command failed: yarn polkadot-exec-tsc --build tsconfig.build.json
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at execSync (file:///home/azakan/polka_explorer/node_modules/@polkadot/dev/scripts/execute.mjs:11:6)
    at main (file:///home/azakan/polka_explorer/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:922:3)
    at file:///home/azakan/polka_explorer/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:956:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25368,
  stdout: null,
  stderr: null
}
```

**Comment by jacogr** [comment]
It is certainly not unused. Import is here -

https://github.com/polkadot-js/apps/blob/bf250faa47486752fe43a748d99f56e71fbc95ec/packages/apps-config/src/endpoints/index.ts#L9

usage is

https://github.com/polkadot-js/apps/blob/bf250faa47486752fe43a748d99f56e71fbc95ec/packages/apps-config/src/endpoints/index.ts#L28

https://github.com/polkadot-js/apps/blob/bf250faa47486752fe43a748d99f56e71fbc95ec/packages/apps-config/src/endpoints/index.ts#L36

https://github.com/polkadot-js/apps/blob/bf250faa47486752fe43a748d99f56e71fbc95ec/packages/apps-config/src/endpoints/index.ts#L62

**Comment by jacogr** [comment]
Closing.
