### ISSUE TITLE
0.9.30 potential issue?

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#8197]
I'm just testing the 0.9.30 / 9300 draft build and seem to be getting some decode issues with getting the event state in polkadot-js 
```
Unable to decode storage system.events:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x000000000748accc420100020000… (index 1/2): {"phase":"FrameSystemPhase","event":"Event","topics":"Vec<H256>"}:: decodeU8a: failed at 0x48accc420100020000… on event (index 1/3): {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index [72, 172]/[72,172]
```
Here's the main stack trace:
```stacktrace
main.d852fdcc.js:19 Error: useCall(society.candidates):: Unable to decode storage system.events: entry 8:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x00003501e803000036f8b1ad2ab2fb28… (index 1/4): {"phase":"FrameSystemPhase","event":"Event","topics":"Vec<H256>"}:: decodeU8a: failed at 0x86035babbef3278f5eb86a3bb2802e0f… on topics (index 2/3): Vec<H256>:: Vec length 718717153 exceeds 65536:: Error: Unable to decode storage system.events: entry 8:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x00003501e803000036f8b1ad2ab2fb28… (index 1/4): {"phase":"FrameSystemPhase","event":"Event","topics":"Vec<H256>"}:: decodeU8a: failed at 0x86035babbef3278f5eb86a3bb2802e0f… on topics (index 2/3): Vec<H256>:: Vec length 718717153 exceeds 65536
    at Qr._newType (polkadot.01.d33a9927.js:1:76773)
    at Qr._formatStorageSetEntry (polkadot.01.d33a9927.js:1:76294)
    at polkadot.01.d33a9927.js:1:76046
    at n.reduce (<anonymous>)
    at Qr._formatStorageSet (polkadot.01.d33a9927.js:1:76016)
    at Qr._formatOutput (polkadot.01.d33a9927.js:1:75549)
    at Qr._formatResult (polkadot.01.d33a9927.js:1:73323)
    at Object.p [as callback] (polkadot.01.d33a9927.js:1:74657)
    at Q.value (polkadot.01.d33a9927.js:1:124650)
    at WebSocket.value (polkadot.01.d33a9927.js:1:123806)
    at d (main.d852fdcc.js:19:87446)
    at main.d852fdcc.js:19:88777
```

Should I try main / is there a branch I can try? or do we think the issue is further down the stack?

**Comment by jacogr** [comment]
See the comment here - https://github.com/polkadot-js/api/issues/5256

**Comment by jacogr** [comment]
Follow the progress for Weights V2 support here - https://github.com/polkadot-js/apps/issues/8188 (all PRs linked through there)
