### ISSUE TITLE
Uncaught error in polkadot-js / apps

### ISSUE THREAD

**Issue by Bruno-Lussan** [polkadot-js/apps#8296]
Bug Report

Hello,
When I try to access my pooled account. I get the following message:

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

useAccountInfo:: Cannot read properties of undefined (reading 'negative'):: TypeError: Cannot read properties of undefined (reading 'negative') at i.isub (https://cloudflare-ipfs.com/ipns/dotapps.io/polkadot.02.f53e8bf5.js:1:98284) at i.sub (https://cloudflare-ipfs.com/ipns/dotapps.io/polkadot.02.f53e8bf5.js:1:98956) at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712258 at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712504 at Object.qa [as useMemo] (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:324453) at t.useMemo (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:610199) at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712188 at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:2:568730 at uie (https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712824) at Ca (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:320072)

Error: useAccountInfo:: Cannot read properties of undefined (reading 'negative'):: TypeError: Cannot read properties of undefined (reading 'negative')
at i.isub (https://cloudflare-ipfs.com/ipns/dotapps.io/polkadot.02.f53e8bf5.js:1:98284)
at i.sub (https://cloudflare-ipfs.com/ipns/dotapps.io/polkadot.02.f53e8bf5.js:1:98956)
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712258
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712504
at Object.qa [as useMemo] (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:324453)
at t.useMemo (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:610199)
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712188
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:2:568730
at uie (https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712824)
at Ca (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:320072)
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:2:568753
at uie (https://cloudflare-ipfs.com/ipns/dotapps.io/main.3769ee0c.js:19:712824)
at Ca (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:320072)
at _s (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:331693)
at Cs (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:330901)
at xl (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:380369)
at yc (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:365985)
at mc (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:365913)
at gc (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:365776)
at oc (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.4ef7e0e3.js:2:362583)

I just destroyed my pool (id:46) on which this account was bounded. Maybe this is the cause? 
Also, I can't unbounded 1KSM of this account : FqnTR6YMzfvkmAS7t8aMeag3BWug3WUukxHT5TU2CP7uAgA

Windows 10
Browser : Google Chrome : Version 107.0.5304.87 (Build officiel) (64 bits)

Parity Polkadot v0.9.30
api v8.12.2
apps v0.117.3

**Comment by jacogr** [comment]
The ipfs version is lagging behind a bit in terms of deployment at this point. (Some issues with the pinning service)

The above could be the cause. Will take a look anyway code-wise to see if something else could be up (that would also affect the up-to-date Polkadot.JS.org/apps)

**Comment by jacogr** [comment]
IPFS should be updated today if CI plays along, see https://github.com/polkadot-js/apps/pull/8320

**Comment by Bruno-Lussan** [comment]
Thanks, now I can see my pooled account.
But I still can't unbound.
https://kusama.subscan.io/extrinsic/15224576-3

**Comment by Bruno-Lussan** [comment]
Yes, it seems that being a member prevents unbound the 1 KSM. In this case how to stop being a member of the pool, I did not find how to do it. Who could help me?

**Comment by kianenigma** [comment]
not stale, will look into asap.

**Comment by kianenigma** [comment]
The issue is that as the last member of the pool, i.e. the depositor, you cannot withdraw to an amount that's too small and would cause the pool nominator to fall below stakings "minNominationBond". If you unbond the whole 1ksm, it should work.

**Comment by kianenigma** [comment]
also, more importantly, you mist first chill the pool: https://paritytech.github.io/substrate/master/pallet_nomination_pools/index.html#pool-management
