### ISSUE TITLE
Fail when trying to open an external motion to Council

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#8402]
I am tryng to submit an external motion to fix the lost dispatch calls on Kusama, and when I try to submit to council I get this:

<img width="1440" alt="Screenshot 2022-11-23 at 15 33 09" src="https://user-images.githubusercontent.com/22815262/203573675-ca634f34-e2d3-4cd3-add6-d1d2f17b68d3.png">

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

createType(Call):: Call: failed decoding democracy.externalProposeMajority:: Struct: failed on args: {"proposal":"{\"_enum\":{\"Legacy\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\"}\",\"Inline\":\"Bytes\",\"Lookup\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\",\\\"len\\\":\\\"u32\\\"}\"}}"}:: Struct: failed on proposal: {"_enum":{"Legacy":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\"}","Inline":"Bytes","Lookup":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\",\"len\":\"u32\"}"}}:: Unable to create Enum via index 131, in Legacy, Inline, Lookup

Error: createType(Call):: Call: failed decoding democracy.externalProposeMajority:: Struct: failed on args: {"proposal":"{\"_enum\":{\"Legacy\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\"}\",\"Inline\":\"Bytes\",\"Lookup\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\",\\\"len\\\":\\\"u32\\\"}\"}}"}:: Struct: failed on proposal: {"_enum":{"Legacy":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\"}","Inline":"Bytes","Lookup":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\",\"len\":\"u32\"}"}}:: Unable to create Enum via index 131, in Legacy, Inline, Lookup
at p (https://polkadot.js.org/apps/polkadot.01.aeb3e1fd.js:1:173410)
at $.createTypeUnsafe (https://polkadot.js.org/apps/polkadot.01.aeb3e1fd.js:1:257241)
at o (https://polkadot.js.org/apps/polkadot.01.aeb3e1fd.js:1:471579)
at Object.a [as externalProposeMajority] (https://polkadot.js.org/apps/polkadot.01.aeb3e1fd.js:1:93754)
at https://polkadot.js.org/apps/main.476ded4a.js:2:1736527
at rl (https://polkadot.js.org/apps/react.01.4d613d94.js:2:181360)
at xc (https://polkadot.js.org/apps/react.01.4d613d94.js:2:201482)
at https://polkadot.js.org/apps/react.01.4d613d94.js:2:200224
at wc (https://polkadot.js.org/apps/react.01.4d613d94.js:2:200289)
at lc (https://polkadot.js.org/apps/react.01.4d613d94.js:2:194045)
```

**Comment by jacogr** [comment]
Ummm... yes, the proposalHash doesn't cater for the new preimages pallet. That would take a bit of tweaking since it needs to detect and cater for both (e.g. work on Kusama & Polkadot at the same time).

The same would apply to democracy proposals.
