### ISSUE TITLE
Crashing on Referenda

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#8938]
Hi Jaco,

Something has changed in the PolkadotJS in the last hours (maybe day) causing PolkadotJs to not load our Alphanet chain.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbase.moonbeam.network#/explorer

There error seems related to referenda:
```
Error: useCounter:: useReferenda:: Assertion failed:: Error: Assertion failed
    at n (polkadot.02.9e2de890.js:1:29655)
    at s.divmod (polkadot.02.9e2de890.js:1:60413)
    at s.div (polkadot.02.9e2de890.js:1:61178)
    at poe (main.3006087c.js:2:2252841)
    at hoe (main.3006087c.js:2:2253043)
    at xoe (main.3006087c.js:2:2254690)
    at main.3006087c.js:2:2255363
    at Object.Qa [as useMemo] (react.01.e784c7f8.js:2:149317)
    at t.useMemo (react.01.e784c7f8.js:2:429412)
    at /apps/main.3006087c.js:2:2255307:: Error: useReferenda:: Assertion failed:: Error: Assertion failed
    at n (polkadot.02.9e2de890.js:1:29655)
    at s.divmod (polkadot.02.9e2de890.js:1:60413)
    at s.div (polkadot.02.9e2de890.js:1:61178)
    at poe (main.3006087c.js:2:2252841)
    at hoe (main.3006087c.js:2:2253043)
    at xoe (main.3006087c.js:2:2254690)
    at main.3006087c.js:2:2255363
    at Object.Qa [as useMemo] (react.01.e784c7f8.js:2:149317)
    at t.useMemo (react.01.e784c7f8.js:2:429412)
    at main.3006087c.js:2:2255307
    at main.3006087c.js:2:2695397
    at koe (main.3006087c.js:2:2255417)
    at main.3006087c.js:2:2255593
    at main.3006087c.js:2:2695374
    at qAe (main.3006087c.js:2:2653829)
    at Sa (react.01.e784c7f8.js:2:144936)
    at Bs (react.01.e784c7f8.js:2:156557)
    at Ss (react.01.e784c7f8.js:2:155765)
    at Cl (react.01.e784c7f8.js:2:205261)
    at bc (react.01.e784c7f8.js:2:190877)
    at main.3006087c.js:2:2695397
    at qAe (main.3006087c.js:2:2653829)
    at Sa (react.01.e784c7f8.js:2:144936)
    at Bs (react.01.e784c7f8.js:2:156557)
    at Ss (react.01.e784c7f8.js:2:155765)
    at Cl (react.01.e784c7f8.js:2:205261)
    at bc (react.01.e784c7f8.js:2:190877)
    at vc (react.01.e784c7f8.js:2:190805)
    at mc (react.01.e784c7f8.js:2:190668)
    at ic (react.01.e784c7f8.js:2:187475)
```

Our alphanet is using referenda (and Moonriver is going to use it this Thursday too) but from a previous version (v0.9.32) than the current substrate (v0.9.37)

**Comment by jacogr** [comment]
Will take a look - but on referenda am really trying to only support the current Substrate version. (It is an absolute nightmare with all old, current, next support everywhere and referenda is still new).

Having said that, it _could_ be something small.

**Comment by jacogr** [comment]
It is due to the usage of `Reciprocal` curves. So I'm guessing it is not an apps UI upgrade (referenda has not been touched), but rather due to a chain upgrade. Never actually tested `Reciprocal` before, so not surprised.

**Comment by jacogr** [comment]
Have a fix on the linked PR that makes it pass - however still unsure if these are actually correct. So not sure which tracks this relates to, but probably would like to check those graphs when they do display. (So there may be some more issues with this)

**Comment by crystalin** [comment]
Awesome Jaco
We did setup those proposal last week, I'm a bit surprised the crash only appears now, but it is working now.
Thank you
