### ISSUE TITLE
Errors shown on Assets Page.  https://polkadot.js.org/apps/#/assets

### ISSUE THREAD

**Issue by GHesericsu** [polkadot-js/apps#8962]
* **I'm submitting a ...**

  - [* ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Can't open Assets page (https://polkadot.js.org/apps/#/assets). It shows this error. 
`Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'toString')

TypeError: Cannot read properties of undefined (reading 'toString')
at D_ (https://polkadot.js.org/apps/main.89ce34d5.js:2:12234884)
at https://polkadot.js.org/apps/main.89ce34d5.js:2:12235298
at https://polkadot.js.org/apps/main.89ce34d5.js:2:12235427
at Array.map (<anonymous>)
at https://polkadot.js.org/apps/main.89ce34d5.js:2:12235194
at rl (https://polkadot.js.org/apps/react.01.f7241a5f.js:2:175326)
at xc (https://polkadot.js.org/apps/react.01.f7241a5f.js:2:195448)
at https://polkadot.js.org/apps/react.01.f7241a5f.js:2:192052
at _ (https://polkadot.js.org/apps/other.01.4a3e5134.js:2:165102)
at I (https://polkadot.js.org/apps/other.01.4a3e5134.js:2:165634)`

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

I'm using Brave browser

  - Version:
  - Environment:

    - [ ] Node.js
    - [ *] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [* ] Other

**Comment by jacogr** [comment]
Which chain?

**Comment by GHesericsu** [comment]
It's my local node's issue. Sorry for the trouble.
