### ISSUE TITLE
"Phantom" multisig approvals appearing on Accounts page

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#9103]
I am seeing "phantom" multisig approvals that don't exist on accounts, and in fact are on some accounts that are not multisigs. When you click on them, a rendering error is displayed.

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'map')

TypeError: Cannot read properties of undefined (reading 'map')
at https://polkadot.js.org/apps/page.380411d44a77a4fd.js:339:15657
at rs (https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:98954)
at Cu (https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:119076)
at https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:117818
at wu (https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:117883)
at su (https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:111639)
at Ho (https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:52410)
at https://polkadot.js.org/apps/modu.d8a2c6c99e89d217.js:2:109044
```

Refreshing the screen does not make them go away, but changing endpoints seems to do so.

At least one other person has had this happen to them. I am happy to provide specific addresses privately, if it will help debug the issue.

Screenshot (with addresses obscured):

<img width="330" alt="Screenshot 2023-03-03 at 18 09 29" src="https://user-images.githubusercontent.com/1417717/222785142-fc343060-453e-4d4a-a32c-177d73aa1109.png">

**Comment by michalisFr** [comment]
We're seeing something similar with the anti-scam bounty multisig. We see a pending call that is for a different multisig.

![Screenshot 2023-03-06 at 3 38 34 PM](https://user-images.githubusercontent.com/45905709/223142520-ee49c401-82ca-445f-a3e2-1b83ca8ae7cf.png)

The multisig call we see is this one:
https://polkadot.subscan.io/extrinsic/14531018-2

This behaviour happens when connected to the following nodes:
- Dotters Net
- Dwellir
- Dweller Tunisia
- IBP Network
- OnFinality
but not on RadiumBlock and Automata (or a light client). With Parity's node it happens intermittently.

**Comment by kianenigma** [comment]
<img width="1685" alt="Screenshot 2023-03-08 at 18 15 33" src="https://user-images.githubusercontent.com/5588131/223882164-b29bde14-eea7-48d3-99d3-13c9064d76d0.png">

Also seeing this anomaly in Rococo, the key1 of the double map is not matching the query, which is wrong right of the bat.

**Comment by MarkEmberRyan** [comment]
We are also seeing this anomoly in the Events Bounty multisig. 

For us, it appears to be related to whether or not there is a valid pending hash in the queue - when we submit a valid multisig call, the phantom hash disappears. When the valid pending call is signed and cleared, the phantom hash returns. Always the same hash, always the same depositor address submitting the phantom call. The activity of the phantom depositor is not reflected on Subscan.

As others stated above, the presence of this anomaly also appears related to which RPC is selected. 

We'd be happy to provide the address of the phantom depositor as well if this would be helpful.

**Comment by jacogr** [comment]
If this is (still) an issue I am sadly missing vital info to take a look. (I am not seeing this on any of my daily use multisigs)

If it happens all the time -

- actual multisig address (so queries can be made to the state)
- which chain and endpoint (funky that it s end to be endpoint related)

**Comment by laboon** [comment]
It is unfortunately still an issue. We are also seeing the same call hashes on the same accounts across different users.

I can email you the accounts I am seeing this on, along with chain and endpoint (and call hashes), unless you prefer a different way for me to privately share information (e.g. Matrix). Just let me know.

**Comment by jacogr** [comment]
Yes, seems to be coming from the RPC node on the above 2 -

![image](https://user-images.githubusercontent.com/1424473/225211434-0856e8bb-d5bb-4d2d-8837-5a735687ca2d.png)

Also tested an old version of the JS API via cli, same results -

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
	const api = await ApiPromise.create({
		provider: new WsProvider('wss://rococo-rpc.polkadot.io')
	});
	const entries = await api.query.multisig.multisigs.entries('5FRz8z6U87LBXLUuBRRy4JtVAh2jhkDSbR5ntCGM2Ds631dJ');

	console.log(entries.map(([k]) => k.toHuman()));
}

main().catch(console.error);
```

**Comment by jacogr** [comment]
Also checked the `.keys` methods, same result, i.e. wrong entries returned.

So that basically means that `state_getKeysPaged` returns wrong entries, so need to start digging through Substrate PRs, e.g. this is a a recent 2-week-old one - https://github.com/paritytech/substrate/pull/13445 (deals with storage iteration)

**Comment by bkchr** [comment]
Okay, maybe we are iterating too far or including at start something that shouldn't be included. 

Cc @koute

**Comment by koute** [comment]
I'll check this.
