### ISSUE TITLE
Uncaught error. Something went wrong with the query and rendering of this component. 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [polkadot-js/apps#9125]
* **I'm submitting a bug** 

- [x] Bug report

* **What is the current behavior and expected behavior?**

Current:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/757125/223701743-9601f5aa-4c7f-4bb7-86c9-2779b981def6.png">

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Invalid character

Error: Invalid character
at n (https://polkadot.js.org/apps/modu.ff40a6106d8303b6.js:1:2975)
at u (https://polkadot.js.org/apps/modu.ff40a6106d8303b6.js:1:3794)
at i._parseBase (https://polkadot.js.org/apps/modu.ff40a6106d8303b6.js:1:6180)
at i._init (https://polkadot.js.org/apps/modu.ff40a6106d8303b6.js:1:4454)
at new i (https://polkadot.js.org/apps/modu.ff40a6106d8303b6.js:1:3269)
at https://polkadot.js.org/apps/comm.6d578ff57f493e65.js:3759:518
at Object.zi [as useState] (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:71481)
at t.useState (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:352305)
at https://polkadot.js.org/apps/comm.6d578ff57f493e65.js:3759:512
at Pi (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:68564)
```

Here https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.composable.finance#/extrinsics

* **Please tell us about your environment:**

  - Version:
  api v10.0.1
  apps v0.124.2-121

  - Environment: Windows

    - [X] Browser
    
Brave
[Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by jacogr** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/1424473/224634598-37e0bff0-615b-4c3e-90cd-66b140286b3f.png)
