### ISSUE TITLE
Preimage error on polkadot-js when upgrading parachain to v0.9.37

### ISSUE THREAD

**Issue by decentration** [polkadot-js/apps#9130]
The issue was initially created on substrate stack [exchange](https://substrate.stackexchange.com/questions/7501/preimage-error-after-upgrading-parachain-to-polkadot-v0-9-37?noredirect=1), but i was advised to generate the bug report here. 

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

The polkadot js frontend is giving an error from the preimage error.

Looking at other chains, it looks like the premimage page has had a revamp, but is not working after upgrading my parachain which does not have any custom changes to preimage.

```
usePreimages:: Cannot read properties of undefined (reading 'statusFor'):: TypeError: Cannot read properties of undefined (reading 'statusFor') at https://polkadot.js.org/apps/page.0bafb3d1aa2e44e4.js:1598:590 at https://polkadot.js.org/apps/comm.6d578ff57f493e65.js:3673:19579 at https://polkadot.js.org/apps/page.0bafb3d1aa2e44e4.js:1604:60 at Pi (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:68564) at xl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:80185) at Pl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:79393) at Bl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:78998) at Bs (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:128847) at bu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114505) at gu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114433)

Error: usePreimages:: Cannot read properties of undefined (reading 'statusFor'):: TypeError: Cannot read properties of undefined (reading 'statusFor')
at https://polkadot.js.org/apps/page.0bafb3d1aa2e44e4.js:1598:590
at https://polkadot.js.org/apps/comm.6d578ff57f493e65.js:3673:19579
at https://polkadot.js.org/apps/page.0bafb3d1aa2e44e4.js:1604:60
at Pi (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:68564)
at xl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:80185)
at Pl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:79393)
at Bl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:78998)
at Bs (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:128847)
at bu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114505)
at gu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114433)
at https://polkadot.js.org/apps/comm.6d578ff57f493e65.js:3673:19602
at https://polkadot.js.org/apps/page.0bafb3d1aa2e44e4.js:1604:60
at Pi (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:68564)
at xl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:80185)
at Pl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:79393)
at Bl (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:78998)
at Bs (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:128847)
at bu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114505)
at gu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114433)
at vu (https://polkadot.js.org/apps/modu.fc3ee6efdaa06c24.js:2:114296)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsoupcan1.jelliedowl.com#/preimages
```

You can see the issue live on [polkadot js](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsoupcan1.jelliedowl.com#/preimages) :

Replicate the [branch](https://github.com/kabocha-network/parachain/tree/kab-release-v0.2.6-soupcan)

**Comment by decentration** [comment]
great stuff, thanks
