### ISSUE TITLE
Uncaught error: https://polkadot.js.org/apps/#/staking/query

### ISSUE THREAD

**Issue by LaplaceTransformS** [polkadot-js/apps#9626]
era points graph timing issue.  Exception thrown immediately.

Polkadot Network
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'enabled')

TypeError: Cannot read properties of undefined (reading 'enabled')
at Object.afterDraw (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:90133)
at p (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:353822)
at Et._notify (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:297210)
at Et.notify (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:296999)
at Gt.notifyPlugins (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:316334)
at Gt.draw (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:311743)
at Gt.render (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:311315)
at Gt.update (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:309373)
at Gt.<anonymous> (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:304939)
at Gt._doResize (https://polkadot.js.org/apps/modu.2743e2706832723b.js:2:358229)

**Comment by LaplaceTransformS** [comment]
The staking dashboard validator metrics shows the era points graph and can be used as a work around.
