### ISSUE TITLE
Uncaught error when calling `api.rpc.syncstate.genSyncSpec` RPC method from the UI

### ISSUE THREAD

**Issue by IkerAlus** [polkadot-js/apps#9723]
In polkadot.js APPs when trying to call the  `api.rpc.syncstate.genSyncSpec` RPC method, I get the following error:

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of null (reading 'toHuman')

TypeError: Cannot read properties of null (reading 'toHuman')
at https://polkadot.js.org/apps/modu.b8aa2d4a2c75f52e.js:50:59712
at Array.reduce (<anonymous>)
at o.toHuman (https://polkadot.js.org/apps/modu.b8aa2d4a2c75f52e.js:50:59677)
at m (https://polkadot.js.org/apps/comm.74dc07db2bb300e2.js:4027:25698)
at p (https://polkadot.js.org/apps/comm.74dc07db2bb300e2.js:4027:26213)
at https://polkadot.js.org/apps/page.5bd3c0a06b4aee4f.js:1333:351
at Array.map (<anonymous>)
at https://polkadot.js.org/apps/page.5bd3c0a06b4aee4f.js:1333:178
at Pi (https://polkadot.js.org/apps/modu.8896a823ddffd6ef.js:2:75841)
at xl (https://polkadot.js.org/apps/modu.8896a823ddffd6ef.js:2:87462)
```

This error has been reproduced in several devices. It happens for both values of the input param `Raw`.

  - [x ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by TarikGul** [comment]
Closing via: https://github.com/polkadot-js/api/pull/5825

Fix will be out in the next release tomorrow
