### ISSUE TITLE
Parachain upgrade not appearing in parachain panel

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#9767]
Parachain upgrading used to appear in the lifecycle of the parachain panel in the relay:

<img width="1685" alt="Screenshot 2023-08-07 at 16 20 29" src="https://github.com/polkadot-js/apps/assets/329248/20ca84a8-1011-460f-839b-d0901e18d1a7">

I also see this error in the console (not sure if related):
```
Error: useCallMulti(...):: Cannot read properties of undefined (reading 'length'):: TypeError: Cannot read properties of undefined (reading 'length')
    at transform (page.4063a55cb52c0ee5.js:1158:1646)
    at comm.74dc07db2bb300e2.js:3892:41692
    at modu.3b4705abeb23323f.js:1:106923
    at modu.b8aa2d4a2c75f52e.js:50:491972
    at u (comm.74dc07db2bb300e2.js:3892:39604)
    at comm.74dc07db2bb300e2.js:3892:41750
    at modu.3b4705abeb23323f.js:1:106923
    at modu.b8aa2d4a2c75f52e.js:50:491972
 ```

**Comment by ap211unitech** [comment]
It seems to be fixed already. However, fix this error message in [PR#11499](https://github.com/polkadot-js/apps/pull/11499)

<img width="299" alt="Image" src="https://github.com/user-attachments/assets/579eaae1-8e74-4e6e-8645-3628cdc39c25" />
