### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'from')

### ISSUE THREAD

**Issue by nicolasochem** [polkadot-js/apps#9806]
I can't make a simple transfer on polkadot using Ledger.

It works with ledger live, so it's not an issue with the app version on ledger. It's on polkadot js.

From web console:

```
comm.50e846a91334b030.js:4115 signAndSend: error: TypeError: Cannot read properties of undefined (reading 'from')
    at r (modu.c42c09a126b3164f.js:50:498303)
    at modu.73a0ce1f494c37b3.js:1:111999
    at f.withApp (modu.73a0ce1f494c37b3.js:1:113063)
    at f.sign (modu.73a0ce1f494c37b3.js:1:112774)
    at v.signPayload (comm.50e846a91334b030.js:4084:3268)
    at a.__internal__signViaSigner (modu.73a0ce1f494c37b3.js:1:77262)
    at modu.73a0ce1f494c37b3.js:1:75970
    at m (modu.5d78a093107b232f.js:2:47283)
    at v (modu.5d78a093107b232f.js:2:47231)
    at s._next (modu.5d78a093107b232f.js:2:44625)
```

**Comment by nicolasochem** [comment]
I'm having the same issue with any type of extrinsic.

**Comment by rajk93** [comment]
I tried to recreate the issue, but everything worked as expected.

## Steps followed:
1. In the Polkadot JS Explorer, I switched to the Polkadot Relay Chain.
2. Forked the chain locally and imported the Ledger account from the Explorer.
3. Sent tokens from the ALICE account to the LEDGER account.
4. Sent an extrinsic from the LEDGER account to the ALICE_STASH account.

The steps are also shown in the attached video preview.

## Preview

https://github.com/user-attachments/assets/c2230de4-617a-4896-9afa-82bc122f77cb
