### ISSUE TITLE
Contracts Tab shows uncaught error

### ISSUE THREAD

**Issue by tadeohepperle** [polkadot-js/apps#9907]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

**What is the current behavior and expected behavior?**

**Current behavior:**

When running a `substrate-contracts-node` locally and navigating to the Contracts tab, this is shown:

![image](https://github.com/polkadot-js/apps/assets/62739623/c9d045fe-8057-4b1c-bdd7-d4634ad85dac)

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'keys')

TypeError: Cannot read properties of undefined (reading 'keys')
at https://polkadot.js.org/apps/page.52e72cfdfbfee15a.js:739:5722
at os (https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:106322)
at Bu (https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:126444)
at https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:125186
at Cu (https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:125251)
at uu (https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:119007)
at $o (https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:59735)
at https://polkadot.js.org/apps/modu.7e3c157f7ba748aa.js:2:116412
```

**Expected behavior:**
I could think of multiple solutions: 
- showing an error message explaining what exactly is going wrong
- not showing the Contracts Tab in the menu in case there is an error
- fixing the root cause of the error and showing the Contracts Tab

**What is the motivation for changing the behavior?**

It would be nice, to not have an uncaught exception displayed anymore :)

**Please tell us about your environment:**

I setup the `contracts-node` locally which is mentioned in the [substrate smart contracts documentation](https://docs.substrate.io/tutorials/smart-contracts/prepare-your-first-contract/). 

I installed it with:
```sh
cargo install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git
```
I ran it with:
```
substrate-contracts-node --log info,runtime::contracts=debug 2>&1
```

  - Environment:
    - [ ] Node.js
    - [x] Browser (Chrome, https://polkadot.js.org/apps/#/explorer)

**Comment by wottpal** [comment]
We're able to find a work around or the reason for this issue? We're having it as well :/

**Comment by ap211unitech** [comment]
Seems to be resolved now. Please feel free to create a new issue if it persists.
